apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-83-tenant/load-app-7ac2a332-84b9-4463-8bd8-a54edd4a4b12/devfile-sample-java-springboot-basic@sha256:6f4b79273b98972290bd48a976dfd9acf96681db251ed0ae0e4bef2898874d46
        name: my-java-springboot
        resources: {}
status: {}
